version: '2'
services:
  logstash:
    image: logstash:2.3.1
    entrypoint: bash -c "logstash --allow-env -f /etc/logstash/conf.d/logstash.conf"
    environment:
     STREAM: ${STREAM} # Your Atom Stream
     AUTH: ${AUTH} # Your pre-shared key to Atom Stream
     SDK_VERSION: 1.0.0
    volumes:
    # Specify the logstash.conf file path on your host
    - <absolute path to your logstash.conf file>:/etc/logstash/conf.d/logstash.conf
    # For more options: https://docs.docker.com/compose/compose-file/#volumes-volume-driver
  filebeat:
    image: prima/filebeat:1.2.3
    links: 
    - logstash
    command: bash -c "`sleep 15` ./bin/filebeat -e -c /etc/filebeat/filebeat.yml"
    volumes:
    #Specify the logstash.conf file path on your host
    - <absolute path to your filebeat.yml file>:/bin/filebeat.yml

    #Specify the path of the log files that you want filebeat to use
    - <absolute path to your log file>:/var/log/log-from-host
